export default [
  {
    _id: '5aac35a610b85cc45fbf7216',
    index: 0,
    guid: '0ddf3477-ccdf-451b-8351-237ca1aee12f',
    isActive: true,
    balance: '$1,012.40',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'blue',
    name: 'Gordon Wells',
    gender: 'male',
    company: 'OPTIQUE',
    email: 'gordonwells@optique.com',
    phone: '+1 (818) 517-3312',
    address: '154 Homecrest Court, Loyalhanna, Iowa, 7823',
    about: 'Lorem esse nostrud laboris adipisicing ut cillum excepteur consequat sunt excepteur proident. Tempor mollit tempor sunt adipisicing excepteur dolor voluptate. Cupidatat minim enim exercitation consequat adipisicing. Ex anim ullamco cupidatat nostrud sunt veniam fugiat ut commodo consequat non sint consequat culpa. Duis ut aliquip culpa ad velit nostrud fugiat. Amet amet consectetur exercitation aute velit laboris consequat aute anim ipsum nulla qui.\r\n',
    registered: '2014-09-05T12:04:48 -03:00',
    tags: [
      'deserunt',
      'officia',
      'adipisicing',
      'tempor',
      'ullamco',
      'aliquip',
      'duis',
    ],
    friends: [
      {
        id: 0,
        name: 'Franks Cantrell',
      },
      {
        id: 1,
        name: 'Lawson Mercado',
      },
      {
        id: 2,
        name: 'Katherine Boyd',
      },
    ],
  },
  {
    _id: '5aac35a6dfc10e80b0f3c5ed',
    index: 1,
    guid: '0b6ca24a-1a49-4f3d-a75d-93b1089f4bbe',
    isActive: false,
    balance: '$2,970.38',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'brown',
    name: 'Shauna Kaufman',
    gender: 'female',
    company: 'NETAGY',
    email: 'shaunakaufman@netagy.com',
    phone: '+1 (987) 593-2593',
    address: '835 Kay Court, Mulino, Mississippi, 8134',
    about: 'Proident cupidatat elit est id nulla adipisicing anim cillum duis est velit sint tempor qui. Cillum officia tempor excepteur eu minim ad duis ex eu voluptate exercitation aute voluptate. Nisi irure reprehenderit minim commodo nulla voluptate eiusmod. Esse culpa sint enim id irure ipsum enim. Amet tempor est qui Lorem elit. Non eiusmod esse excepteur proident ut in veniam voluptate dolore occaecat minim.\r\n',
    registered: '2014-06-10T02:48:40 -03:00',
    tags: [
      'commodo',
      'fugiat',
      'anim',
      'velit',
      'ex',
      'commodo',
      'pariatur',
    ],
    friends: [
      {
        id: 0,
        name: 'Barton Cooley',
      },
      {
        id: 1,
        name: 'Robinson Mcintosh',
      },
      {
        id: 2,
        name: 'Roslyn Dillon',
      },
    ],
  },
  {
    _id: '5aac35a6f75dc482120b561e',
    index: 2,
    guid: 'b6ec1f87-9fe3-4ee9-bf77-48daf78d8a2d',
    isActive: true,
    balance: '$1,631.14',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'green',
    name: 'Crawford Mann',
    gender: 'male',
    company: 'CUJO',
    email: 'crawfordmann@cujo.com',
    phone: '+1 (988) 521-2150',
    address: '530 Dinsmore Place, Starks, Utah, 4262',
    about: 'Exercitation aliqua proident enim veniam adipisicing laborum consequat ex do non enim id officia deserunt. Labore ad qui tempor minim aute irure incididunt duis anim ut. Cillum aliquip fugiat cillum magna tempor occaecat. Sit consectetur deserunt eiusmod reprehenderit nulla Lorem.\r\n',
    registered: '2015-08-01T01:14:47 -03:00',
    tags: [
      'voluptate',
      'qui',
      'Lorem',
      'Lorem',
      'sint',
      'adipisicing',
      'aliquip',
    ],
    friends: [
      {
        id: 0,
        name: 'Knox Fleming',
      },
      {
        id: 1,
        name: 'Oneil Hubbard',
      },
      {
        id: 2,
        name: 'Hill Fry',
      },
    ],
  },
  {
    _id: '5aac35a6399441a70713829c',
    index: 3,
    guid: 'ec75eceb-dc68-4848-8930-62812dad47d0',
    isActive: false,
    balance: '$1,345.66',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: 'Le Nunez',
    gender: 'male',
    company: 'ISODRIVE',
    email: 'lenunez@isodrive.com',
    phone: '+1 (830) 498-3275',
    address: '288 Tehama Street, Martinez, Florida, 8184',
    about: 'Consectetur excepteur tempor exercitation non esse nulla tempor non labore non proident. Ex laborum irure aliquip ad occaecat tempor proident aute ullamco cupidatat aute Lorem est magna. Aliquip magna aliqua et quis do. Nulla cupidatat minim voluptate est incididunt sunt labore et tempor sint veniam et.\r\n',
    registered: '2015-10-17T07:57:41 -03:00',
    tags: [
      'ipsum',
      'esse',
      'sit',
      'non',
      'magna',
      'fugiat',
      'occaecat',
    ],
    friends: [
      {
        id: 0,
        name: 'Sharp Joyner',
      },
      {
        id: 1,
        name: 'Pratt Carrillo',
      },
      {
        id: 2,
        name: 'Lea Gonzales',
      },
    ],
  },
  {
    _id: '5aac35a68421ddc643fe900b',
    index: 4,
    guid: '0eae6ce7-01e5-4bad-9d1f-7946aa542b55',
    isActive: true,
    balance: '$3,538.81',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'brown',
    name: 'Jacobson Morris',
    gender: 'male',
    company: 'XINWARE',
    email: 'jacobsonmorris@xinware.com',
    phone: '+1 (892) 482-2623',
    address: '859 Cheever Place, Westboro, Louisiana, 3781',
    about: 'Dolore qui in enim deserunt occaecat ipsum veniam elit Lorem duis sunt sint magna. Eiusmod enim eiusmod irure officia deserunt ipsum dolore incididunt laborum aute mollit ex. Id deserunt nisi culpa irure ea consectetur cupidatat culpa aliqua nostrud est ut tempor nisi. Cupidatat Lorem velit non eu laborum non aute ex mollit minim pariatur ipsum. Incididunt voluptate et enim aute officia sunt qui sint amet aliquip voluptate excepteur in. Magna proident sunt veniam exercitation irure laboris dolore esse.\r\n',
    registered: '2016-04-19T08:22:58 -03:00',
    tags: [
      'et',
      'nostrud',
      'elit',
      'amet',
      'ex',
      'elit',
      'ad',
    ],
    friends: [
      {
        id: 0,
        name: 'Fernandez Tucker',
      },
      {
        id: 1,
        name: 'Houston Waters',
      },
      {
        id: 2,
        name: 'Lowery Donovan',
      },
    ],
  },
  {
    _id: '5aac35a639206dd83c70a029',
    index: 5,
    guid: 'a1c4b025-2d13-49bf-af79-ab03737f7ab6',
    isActive: true,
    balance: '$1,193.59',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'blue',
    name: 'Chandler Wilkerson',
    gender: 'male',
    company: 'CINCYR',
    email: 'chandlerwilkerson@cincyr.com',
    phone: '+1 (917) 471-3398',
    address: '228 Luquer Street, Clayville, Connecticut, 4071',
    about: 'Et veniam cillum dolore sunt. Fugiat id ullamco elit in velit. Aute in non Lorem nulla minim sint ipsum. Sit sit veniam anim reprehenderit ut est tempor sunt eu laborum proident. Amet ad magna proident aute et ad laboris quis ullamco irure incididunt proident elit. Reprehenderit labore reprehenderit laborum mollit aute nulla.\r\n',
    registered: '2014-12-07T12:36:12 -02:00',
    tags: [
      'ad',
      'non',
      'non',
      'ut',
      'ea',
      'elit',
      'mollit',
    ],
    friends: [
      {
        id: 0,
        name: 'Lisa Battle',
      },
      {
        id: 1,
        name: 'Hester Ferrell',
      },
      {
        id: 2,
        name: 'Lora Phillips',
      },
    ],
  },
  {
    _id: '5aac35a63f89626ab1a1ce7a',
    index: 6,
    guid: 'fe19d7ac-7de2-440e-acab-8023a40d1f68',
    isActive: true,
    balance: '$1,245.12',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'green',
    name: 'Thornton Williams',
    gender: 'male',
    company: 'DEVILTOE',
    email: 'thorntonwilliams@deviltoe.com',
    phone: '+1 (978) 586-3550',
    address: '601 Garden Street, Biehle, New Mexico, 189',
    about: 'Consectetur est ut nostrud aliqua qui enim ipsum officia qui quis sit. Lorem consectetur do magna id. Reprehenderit et qui cupidatat quis et. Ea anim ex dolore mollit reprehenderit sunt Lorem eu ad consequat enim. Labore eiusmod cupidatat cillum enim do elit in dolore excepteur sunt enim fugiat. Esse magna deserunt est non.\r\n',
    registered: '2014-01-21T03:06:12 -02:00',
    tags: [
      'excepteur',
      'laboris',
      'elit',
      'sit',
      'nostrud',
      'consectetur',
      'amet',
    ],
    friends: [
      {
        id: 0,
        name: 'Briana Allison',
      },
      {
        id: 1,
        name: 'Valarie Mueller',
      },
      {
        id: 2,
        name: 'Reese Salas',
      },
    ],
  },
  {
    _id: '5aac35a652b46d59af621594',
    index: 7,
    guid: '1c543cce-218a-41b1-a028-d7215e4bae73',
    isActive: false,
    balance: '$3,598.10',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'brown',
    name: 'Ora Villarreal',
    gender: 'female',
    company: 'NETBOOK',
    email: 'oravillarreal@netbook.com',
    phone: '+1 (906) 420-3054',
    address: '266 Nelson Street, Neibert, Arizona, 8016',
    about: 'Qui ipsum minim amet nostrud reprehenderit. Qui officia ad mollit non mollit aliqua duis cillum. Exercitation proident sint adipisicing incididunt ea excepteur culpa ex aliquip.\r\n',
    registered: '2016-10-26T05:43:50 -03:00',
    tags: [
      'cillum',
      'ipsum',
      'ea',
      'aliqua',
      'dolore',
      'occaecat',
      'duis',
    ],
    friends: [
      {
        id: 0,
        name: 'Harriet Deleon',
      },
      {
        id: 1,
        name: 'Erica Estes',
      },
      {
        id: 2,
        name: 'Beverly Hurley',
      },
    ],
  },
];
